from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv
from db import init_db, init_certificates_table, get_connection, write_certificate, get_certificate
from pipeline import analyze
from detection.multimodal_signal import get_multimodal_score
from audit import write_log_entry, get_log, update_status, write_appeal
import uuid

load_dotenv()

app = Flask(__name__)
init_db()
init_certificates_table()

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()

    if not data or "creator_id" not in data:
        return jsonify({"error": "Request must include 'creator_id'."}), 400

    has_text = "text" in data
    has_image_description = "image_description" in data

    if not has_text and not has_image_description:
        return jsonify({"error": "Request must include 'text' and/or 'image_description'."}), 400

    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())
    certificate = get_certificate(creator_id)
    is_verified = certificate is not None

    # --- Text pipeline ---
    text_result = None
    if has_text:
        text_result = analyze(data["text"])

    # --- Image description pipeline ---
    image_result = None
    if has_image_description:
        image_result = get_multimodal_score(data["image_description"])

    # --- Combine if both present ---
    if text_result and image_result:
        combined_score = round((0.60 * text_result["combined_score"]) + (0.40 * image_result["score"]), 4)
        content_type = "multimodal"
    elif text_result:
        combined_score = text_result["combined_score"]
        content_type = "text"
    else:
        combined_score = image_result["score"]
        content_type = "image_description"

    # --- Label generation ---
    if is_verified:
        transparency_label = (
            "Attribution Notice: This creator has completed identity verification and "
            "holds a Verified Human certificate. Content from verified creators is "
            "still analyzed, but appeals are prioritized. "
            f"| Certificate issued: {certificate['verified_at']} | Confidence: Verified"
        )
        confidence_label = "verified_human"
        attribution_result = "verified_human"
    elif combined_score >= 0.65:
        attribution_result = "likely_ai"
        confidence_label = "high_confidence_ai"
        transparency_label = (
            "Attribution Notice: Our system found strong indicators that this content "
            "may have been AI-generated. This is based on an analysis of writing patterns "
            "and style — not a definitive judgment. If you created this work yourself, "
            "you can submit an appeal. | Confidence: High"
        )
    elif combined_score <= 0.35:
        attribution_result = "likely_human"
        confidence_label = "high_confidence_human"
        transparency_label = (
            "Attribution Notice: Our system found no strong indicators of AI generation "
            "in this content. It appears consistent with human-written work. | Confidence: High"
        )
    else:
        attribution_result = "uncertain"
        confidence_label = "uncertain"
        transparency_label = (
            "Attribution Notice: Our system could not confidently determine whether this "
            "content was written by a person or generated by AI. The signals were mixed or "
            "inconclusive. No action has been taken. If you have concerns, you can submit "
            "an appeal. | Confidence: Low"
        )

    write_log_entry(
        content_id=content_id,
        creator_id=creator_id,
        content_preview=(data.get("text", data.get("image_description", "")))[:120],
        llm_score=text_result["llm_score"] if text_result else None,
        stylometric_score=text_result["stylometric_score"] if text_result else None,
        combined_score=combined_score,
        attribution_result=attribution_result,
        confidence_label=confidence_label,
        transparency_label=transparency_label,
        status="reviewed"
    )

    response = {
        "content_id": content_id,
        "content_type": content_type,
        "attribution": attribution_result,
        "confidence": combined_score,
        "confidence_label": confidence_label,
        "label": transparency_label,
        "provenance_certificate": is_verified,
    }

    if text_result:
        response["text_signals"] = {
            "llm_score": text_result["llm_score"],
            "llm_reasoning": text_result["llm_reasoning"],
            "stylometric_score": text_result["stylometric_score"],
            "stylometric_metrics": text_result["stylometric_metrics"],
            "readability_score": text_result["readability_score"],
            "readability_metrics": text_result["readability_metrics"],
            "signals_in_conflict": text_result["signals_in_conflict"],
            "signal_range": text_result["signal_range"]
        }

    if image_result:
        response["image_signals"] = {
            "image_description_score": image_result["score"],
            "image_description_reasoning": image_result["reasoning"]
        }

    if is_verified:
        response["certificate"] = {
            "verified_at": certificate["verified_at"],
            "verification_method": certificate["verification_method"]
        }

    return jsonify(response), 200


@app.route("/verify", methods=["POST"])
def verify():
    data = request.get_json()

    if not data or "creator_id" not in data or "attestation" not in data:
        return jsonify({"error": "Request must include 'creator_id' and 'attestation' fields."}), 400

    creator_id = data["creator_id"]
    attestation = data["attestation"]

    if len(attestation.strip()) < 20:
        return jsonify({"error": "Attestation must be at least 20 characters. Describe your creative process."}), 400

    existing = get_certificate(creator_id)
    if existing:
        return jsonify({
            "message": "Creator already holds a Verified Human certificate.",
            "creator_id": creator_id,
            "verified_at": existing["verified_at"]
        }), 200

    success = write_certificate(
        creator_id=creator_id,
        verification_method="self_attestation_v1",
        attestation=attestation
    )

    if not success:
        return jsonify({"error": "Could not issue certificate. Try again."}), 500

    return jsonify({
        "message": "Verified Human certificate issued. Future submissions from this creator will display a verified label.",
        "creator_id": creator_id,
        "verification_method": "self_attestation_v1",
        "certificate_status": "verified"
    }), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()

    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Request must include 'content_id' and 'creator_reasoning' fields."}), 400

    content_id = data["content_id"]
    creator_reasoning = data["creator_reasoning"]

    found = update_status(content_id, "under_review")
    if not found:
        return jsonify({"error": f"No submission found with content_id '{content_id}'."}), 404

    accepted = write_appeal(content_id, creator_reasoning)
    if not accepted:
        return jsonify({
            "message": "An open appeal already exists for this content.",
            "content_id": content_id,
            "status": "under_review"
        }), 200

    return jsonify({
        "message": "Appeal received. Your submission has been marked as under review.",
        "content_id": content_id,
        "status": "under_review"
    }), 200


@app.route("/log", methods=["GET"])
def log():
    entries = get_log()
    return jsonify({"entries": entries}), 200


@app.route("/analytics", methods=["GET"])
def analytics():
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("SELECT COUNT(*) FROM audit_log")
    total_submissions = cursor.fetchone()[0]

    cursor.execute("SELECT attribution_result, COUNT(*) FROM audit_log GROUP BY attribution_result")
    verdict_counts = {row[0]: row[1] for row in cursor.fetchall()}

    cursor.execute("SELECT COUNT(*) FROM appeals")
    total_appeals = cursor.fetchone()[0]

    appeal_rate = round(total_appeals / total_submissions, 4) if total_submissions > 0 else 0.0

    cursor.execute("SELECT AVG(combined_score) FROM audit_log")
    avg_confidence = cursor.fetchone()[0]
    avg_confidence = round(avg_confidence, 4) if avg_confidence else 0.0

    cursor.execute("""
        SELECT AVG(combined_score) FROM audit_log
        WHERE submitted_at >= datetime('now', '-1 hour')
    """)
    avg_confidence_last_hour = cursor.fetchone()[0]
    avg_confidence_last_hour = round(avg_confidence_last_hour, 4) if avg_confidence_last_hour else 0.0

    cursor.execute("""
        SELECT attribution_result, COUNT(*) as count
        FROM audit_log
        WHERE submitted_at >= datetime('now', '-1 hour')
        GROUP BY attribution_result
    """)
    recent_verdicts = {row[0]: row[1] for row in cursor.fetchall()}

    conn.close()

    ai_count = verdict_counts.get("likely_ai", 0)
    human_count = verdict_counts.get("likely_human", 0)
    uncertain_count = verdict_counts.get("uncertain", 0)

    return jsonify({
        "total_submissions": total_submissions,
        "verdict_breakdown": {
            "likely_ai": ai_count,
            "likely_human": human_count,
            "uncertain": uncertain_count
        },
        "ai_ratio": round(ai_count / total_submissions, 4) if total_submissions > 0 else 0.0,
        "human_ratio": round(human_count / total_submissions, 4) if total_submissions > 0 else 0.0,
        "uncertain_ratio": round(uncertain_count / total_submissions, 4) if total_submissions > 0 else 0.0,
        "total_appeals": total_appeals,
        "appeal_rate": appeal_rate,
        "avg_confidence_score_all_time": avg_confidence,
        "avg_confidence_score_last_hour": avg_confidence_last_hour,
        "recent_verdict_breakdown_last_hour": recent_verdicts
    }), 200


if __name__ == "__main__":
    app.run(debug=True)
