from detection.llm_signal import get_llm_score
from detection.stylometric import get_stylometric_score

LLM_WEIGHT = 0.60
STYLO_WEIGHT = 0.40

THRESHOLD_AI = 0.65
THRESHOLD_HUMAN = 0.35


def analyze(text: str) -> dict:
    llm_result = get_llm_score(text)
    stylo_result = get_stylometric_score(text)

    llm_score = llm_result["score"]
    stylo_score = stylo_result["score"]

    combined_score = round((LLM_WEIGHT * llm_score) + (STYLO_WEIGHT * stylo_score), 4)

    attribution_result, confidence_label, transparency_label = _generate_label(combined_score)

    return {
        "llm_score": llm_score,
        "llm_reasoning": llm_result["reasoning"],
        "stylometric_score": stylo_score,
        "stylometric_metrics": stylo_result["metrics"],
        "combined_score": combined_score,
        "attribution_result": attribution_result,
        "confidence_label": confidence_label,
        "transparency_label": transparency_label
    }


def _generate_label(score: float) -> tuple:
    if score >= THRESHOLD_AI:
        attribution = "likely_ai"
        confidence_label = "high_confidence_ai"
        label = (
            "Attribution Notice: Our system found strong indicators that this content "
            "may have been AI-generated. This is based on an analysis of writing patterns "
            "and style — not a definitive judgment. If you created this work yourself, "
            "you can submit an appeal. | Confidence: High"
        )
    elif score <= THRESHOLD_HUMAN:
        attribution = "likely_human"
        confidence_label = "high_confidence_human"
        label = (
            "Attribution Notice: Our system found no strong indicators of AI generation "
            "in this content. It appears consistent with human-written work. | Confidence: High"
        )
    else:
        attribution = "uncertain"
        confidence_label = "uncertain"
        label = (
            "Attribution Notice: Our system could not confidently determine whether this "
            "content was written by a person or generated by AI. The signals were mixed or "
            "inconclusive. No action has been taken. If you have concerns, you can submit "
            "an appeal. | Confidence: Low"
        )

    return attribution, confidence_label, label


if __name__ == "__main__":
    test_inputs = [
        ("Clearly AI", "Artificial intelligence represents a transformative paradigm shift in modern society. It is important to note that while the benefits of AI are numerous, it is equally essential to consider the ethical implications. Furthermore, stakeholders across various sectors must collaborate to ensure responsible deployment."),
        ("Clearly human", "ok so i finally tried that new ramen place downtown and honestly? underwhelming. the broth was fine but they put WAY too much sodium in it and i was thirsty for like three hours after. my friend got the spicy version and said it was better. probably won't go back unless someone drags me there"),
        ("Borderline formal", "The relationship between monetary policy and asset price inflation has been extensively studied in the literature. Central banks face a fundamental tension between their mandate for price stability and the unintended consequences of prolonged low interest rates on equity and real estate valuations."),
        ("Borderline edited AI", "I've been thinking a lot about remote work lately. There are genuine tradeoffs — flexibility and no commute on one side, isolation and blurred work-life boundaries on the other. Studies show productivity varies widely by individual and role type.")
    ]

    for label, text in test_inputs:
        print(f"\n--- {label} ---")
        result = analyze(text)
        print(f"LLM Score:         {result['llm_score']}")
        print(f"Stylometric Score: {result['stylometric_score']}")
        print(f"Combined Score:    {result['combined_score']}")
        print(f"Attribution:       {result['attribution_result']}")
        print(f"Confidence:        {result['confidence_label']}")
