import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

def get_llm_score(text: str) -> dict:
    prompt = f"""You are an expert at distinguishing human-written text from AI-generated text.

Analyze the following text and assess whether it was written by a human or generated by an AI.

Consider:
- Semantic coherence and predictability
- Phrasing naturalness and idiosyncrasy
- Structural regularity vs. irregularity
- Stylistic consistency (AI tends to be very consistent; humans vary)

Return ONLY a JSON object in this exact format, no explanation:
{{
  "score": <float between 0.0 and 1.0>,
  "reasoning": "<one sentence explanation>"
}}

Where 0.0 = strongly human-written, 1.0 = strongly AI-generated.

Text to analyze:
\"\"\"
{text}
\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    import json
    parsed = json.loads(raw)
    score = float(parsed["score"])
    score = max(0.0, min(1.0, score))

    return {
        "score": score,
        "reasoning": parsed.get("reasoning", "")
    }


if __name__ == "__main__":
    test_inputs = [
        "The sun dipped below the horizon, painting the sky in hues of amber and rose. I sat on the porch, coffee in hand, watching the neighborhood slowly go quiet.",
        "Artificial intelligence (AI) refers to the simulation of human intelligence in machines that are programmed to think and learn. It encompasses a wide range of technologies and applications.",
        "idk man it was just like. one of those days where nothing goes right but also nothing goes that wrong either. you know?"
    ]

    for i, text in enumerate(test_inputs, 1):
        print(f"\n--- Test {i} ---")
        print(f"Text: {text[:80]}...")
        result = get_llm_score(text)
        print(f"LLM Score: {result['score']}")
        print(f"Reasoning: {result['reasoning']}")
