import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


def get_multimodal_score(image_description: str) -> dict:
    prompt = f"""You are an expert at detecting whether image descriptions were written by a human or generated by AI.

Analyze the following image description and assess whether it was written by a human or generated by an AI system.

Consider:
- Does it use formulaic, overly comprehensive language typical of AI image captioning?
- Does it list features systematically (foreground, background, lighting) in a structured way?
- Is the language natural and selective (humans notice what stands out) or exhaustive and uniform?
- Are there subjective reactions, personal emphasis, or irregular focus typical of human observation?

Return ONLY a JSON object in this exact format, no explanation:
{{
  "score": <float between 0.0 and 1.0>,
  "reasoning": "<one sentence explanation>"
}}

Where 0.0 = strongly human-written description, 1.0 = strongly AI-generated description.

Image description to analyze:
\"\"\"
{image_description}
\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()
    parsed = json.loads(raw)
    score = float(parsed["score"])
    score = max(0.0, min(1.0, score))

    return {
        "score": round(score, 4),
        "reasoning": parsed.get("reasoning", "")
    }
